// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void FlechaSeleccion_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Spinner1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label11;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image9;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image10;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_telefono_c_png);    // assets/Telefono_C.png
LV_IMG_DECLARE(ui_img_flecha_izq_png);    // assets/Flecha Izq.png
LV_IMG_DECLARE(ui_img_telefonomp_png);    // assets/TelefonoMP.png
LV_IMG_DECLARE(ui_img_vending_png);    // assets/Vending.png
LV_IMG_DECLARE(ui_img_f600_png);    // assets/F600.png
LV_IMG_DECLARE(ui_img_f617_png);    // assets/F617.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
