// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_VM_Ver2.0

#ifndef _SQUARELINE_VM_VER2_0_UI_H
#define _SQUARELINE_VM_VER2_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void FlechaSeleccion_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Producto;
extern lv_obj_t * ui_Precio;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Spinner1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image9;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image10;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image5;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image7;
// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image8;
// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image12;
// SCREEN: ui_Screen11
void ui_Screen11_screen_init(void);
extern lv_obj_t * ui_Screen11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image13;
// SCREEN: ui_Screen12
void ui_Screen12_screen_init(void);
extern lv_obj_t * ui_Screen12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image14;
// SCREEN: ui_Screen13
void ui_Screen13_screen_init(void);
extern lv_obj_t * ui_Screen13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image15;
// SCREEN: ui_Screen14
void ui_Screen14_screen_init(void);
extern lv_obj_t * ui_Screen14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image16;
// SCREEN: ui_Screen15
void ui_Screen15_screen_init(void);
extern lv_obj_t * ui_Screen15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image17;
// SCREEN: ui_Screen16
void ui_Screen16_screen_init(void);
extern lv_obj_t * ui_Screen16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image18;
// SCREEN: ui_Screen17
void ui_Screen17_screen_init(void);
extern lv_obj_t * ui_Screen17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image19;
// SCREEN: ui_Screen18
void ui_Screen18_screen_init(void);
extern lv_obj_t * ui_Screen18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image20;
// SCREEN: ui_Screen19
void ui_Screen19_screen_init(void);
extern lv_obj_t * ui_Screen19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image21;
// SCREEN: ui_Screen20
void ui_Screen20_screen_init(void);
extern lv_obj_t * ui_Screen20;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_telefono_c_png);    // assets/Telefono_C.png
LV_IMG_DECLARE(ui_img_flecha_izq_png);    // assets/Flecha Izq.png
LV_IMG_DECLARE(ui_img_telefonomp_png);    // assets/TelefonoMP.png
LV_IMG_DECLARE(ui_img_vending_png);    // assets/Vending.png
LV_IMG_DECLARE(ui_img_f600_png);    // assets/F600.png
LV_IMG_DECLARE(ui_img_f617_png);    // assets/F617.png



LV_FONT_DECLARE(ui_font_Exo24);
LV_FONT_DECLARE(ui_font_Exo32);
LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
