// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_VM_Ver1.0

#ifndef _SQUARELINE_VM_VER1_0_UI_H
#define _SQUARELINE_VM_VER1_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void FlechaSeleccion_Animation(lv_obj_t * TargetObject, int delay);
void Emoji_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Pantalla
void ui_Pantalla_screen_init(void);
extern lv_obj_t * ui_Pantalla;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Producto;
extern lv_obj_t * ui_Precio;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image9;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image10;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_telefono_c_png);    // assets/Telefono_C.png
LV_IMG_DECLARE(ui_img_flecha_izq_png);    // assets/Flecha Izq.png
LV_IMG_DECLARE(ui_img_telefonomp_png);    // assets/TelefonoMP.png
LV_IMG_DECLARE(ui_img_vending_png);    // assets/Vending.png
LV_IMG_DECLARE(ui_img_f600_png);    // assets/F600.png
LV_IMG_DECLARE(ui_img_f617_png);    // assets/F617.png



LV_FONT_DECLARE(ui_font_Exo24);
LV_FONT_DECLARE(ui_font_Exo32);
LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
