// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_Image4_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Label5_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Telefono_create_hook(lv_obj_t * comp)
{
}
