// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_LABEL5_H
#define _UI_COMP_LABEL5_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label5
#define UI_COMP_LABEL5_LABEL5 0
#define _UI_COMP_LABEL5_NUM 1
lv_obj_t * ui_Label5_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
