// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_VM_Ver1.0

#ifndef _UI_COMP_TELEFONO_H
#define _UI_COMP_TELEFONO_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Telefono
#define UI_COMP_TELEFONO_TELEFONO 0
#define _UI_COMP_TELEFONO_NUM 1
lv_obj_t * ui_Telefono_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
