// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_VM_Ver2.0

#ifndef _SQUARELINE_VM_VER2_0_UI_COMP_HOOK_H
#define _SQUARELINE_VM_VER2_0_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Image4_create_hook(lv_obj_t * comp);
void ui_comp_Label5_create_hook(lv_obj_t * comp);
void ui_comp_Telefono_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
