// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_VM_Ver1.0

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 222);
    lv_obj_set_height(ui_Panel1, 109);
    lv_obj_set_x(ui_Panel1, -4);
    lv_obj_set_y(ui_Panel1, -100);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x01BF3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Producto = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Producto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Producto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Producto, -14);
    lv_obj_set_y(ui_Producto, -15);
    lv_obj_set_align(ui_Producto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Producto, "Producto");
    lv_obj_set_style_text_font(ui_Producto, &ui_font_Exo32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Precio = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Precio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Precio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Precio, -4);
    lv_obj_set_y(ui_Precio, 28);
    lv_obj_set_align(ui_Precio, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Precio, "$350");
    lv_obj_set_style_text_font(ui_Precio, &ui_font_Exo32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image11, &ui_img_telefonomp_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 193
    lv_obj_set_x(ui_Image11, 2);
    lv_obj_set_y(ui_Image11, 153);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_flecha_izq_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -4);
    lv_obj_set_y(ui_Image2, 58);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image2, 2700);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_height(ui_Label7, 57);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 6);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label7, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label7, "    Por favor \nRealice el pago \nen su TELEFONO\n\n");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Exo24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);

}
